// <auto-generated />
using System;
using BackendTechnicalAssetsManagement.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendTechnicalAssetsManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426084236_AddRfidCodeToStudent")]
    partial class AddRfidCodeToStudent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BorrowedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemSerialNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("LentItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewStatus")
                        .HasColumnType("text");

                    b.Property<string>("PreviousStatus")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReservedFor")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LentItemId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemModel")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("RfidUid")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ArchiveItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000005"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "6-foot HDMI cable, retired from service.",
                            ImageUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/items/item_06_hdmi_short.png",
                            ItemMake = "Generic",
                            ItemName = "HDMI Cable 6ft",
                            ItemType = "Cable",
                            Location = "Storage Room",
                            RfidUid = "RFID-ITEM-006",
                            SerialNumber = "SN-HDMI-006",
                            Status = "Archived",
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000006"),
                            Category = "MediaEquipment",
                            Condition = "Defective",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "USB condenser microphone, defective.",
                            ImageUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/items/item_07_usb_mic.png",
                            ItemMake = "Blue",
                            ItemName = "USB Microphone",
                            ItemType = "Microphone",
                            Location = "Storage Room",
                            RfidUid = "RFID-ITEM-007",
                            SerialNumber = "SN-MIC-007",
                            Status = "Archived",
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000007"),
                            Category = "Electronics",
                            Condition = "NeedRepair",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wireless optical mouse, needs repair.",
                            ImageUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/items/item_08_mouse.png",
                            ItemMake = "Logitech",
                            ItemName = "Wireless Mouse",
                            ItemType = "Peripheral",
                            Location = "Storage Room",
                            RfidUid = "RFID-ITEM-008",
                            SerialNumber = "SN-MOUSE-008",
                            Status = "Archived",
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000008"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "15-foot extension wire, retired.",
                            ImageUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/items/item_09_extension.png",
                            ItemMake = "Generic",
                            ItemName = "Extension Wire 15ft",
                            ItemType = "Cable",
                            Location = "Storage Room",
                            RfidUid = "RFID-ITEM-009",
                            SerialNumber = "SN-EXT-009",
                            Status = "Archived",
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000009"),
                            Category = "Electronics",
                            Condition = "Refurbished",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "7-port USB 3.0 hub, refurbished.",
                            ImageUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/items/item_10_usb_hub.png",
                            ItemMake = "Anker",
                            ItemName = "USB Hub 7-Port",
                            ItemType = "Peripheral",
                            Location = "Storage Room",
                            RfidUid = "RFID-ITEM-010",
                            SerialNumber = "SN-HUB-010",
                            Status = "Archived",
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveLentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FrontStudentIdPictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("GuestImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsHiddenFromUser")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReservedFor")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Room")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("text");

                    b.Property<string>("StudentRfid")
                        .HasColumnType("text");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagUid")
                        .HasColumnType("text");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("text");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("ArchiveLentItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000010"),
                            BorrowerFullName = "Archived Teacher",
                            BorrowerRole = "Teacher",
                            CreatedAt = new DateTime(2025, 1, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsHiddenFromUser = false,
                            ItemId = new Guid("00000005-0000-0000-0000-000000000006"),
                            ItemName = "HDMI Cable 6ft",
                            LentAt = new DateTime(2025, 1, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            ReturnedAt = new DateTime(2025, 1, 14, 11, 0, 0, 0, DateTimeKind.Utc),
                            Room = "Room 301",
                            Status = "Returned",
                            SubjectTimeSchedule = "MA101 - 11:00 AM",
                            TeacherFullName = "Archived Teacher",
                            TeacherId = new Guid("00000003-0000-0000-0000-000000000005"),
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000003-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000011"),
                            BorrowerFullName = "Archived Student",
                            BorrowerRole = "Student",
                            CreatedAt = new DateTime(2024, 12, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsHiddenFromUser = false,
                            ItemId = new Guid("00000005-0000-0000-0000-000000000007"),
                            ItemName = "USB Microphone",
                            LentAt = new DateTime(2024, 12, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            ReturnedAt = new DateTime(2024, 12, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            Room = "Lab 201",
                            Status = "Returned",
                            StudentIdNumber = "2022-0099",
                            SubjectTimeSchedule = "IT301 - 2:00 PM",
                            TeacherFullName = "",
                            UpdatedAt = new DateTime(2024, 12, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000004-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000012"),
                            BorrowerFullName = "Juan Dela Cruz",
                            BorrowerRole = "Student",
                            CreatedAt = new DateTime(2024, 11, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsHiddenFromUser = false,
                            ItemId = new Guid("00000005-0000-0000-0000-000000000008"),
                            ItemName = "Wireless Mouse",
                            LentAt = new DateTime(2024, 11, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            ReturnedAt = new DateTime(2024, 11, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            Room = "Lab 101",
                            Status = "Returned",
                            StudentIdNumber = "2023-0001",
                            SubjectTimeSchedule = "CS201 - 8:00 AM",
                            TeacherFullName = "",
                            UpdatedAt = new DateTime(2024, 11, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000004-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000013"),
                            BorrowerFullName = "Alice Williams",
                            BorrowerRole = "Teacher",
                            CreatedAt = new DateTime(2024, 10, 15, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsHiddenFromUser = false,
                            ItemId = new Guid("00000005-0000-0000-0000-000000000009"),
                            ItemName = "Extension Wire 15ft",
                            LentAt = new DateTime(2024, 10, 15, 15, 0, 0, 0, DateTimeKind.Utc),
                            ReturnedAt = new DateTime(2024, 10, 17, 15, 0, 0, 0, DateTimeKind.Utc),
                            Room = "Room 201",
                            Status = "Returned",
                            SubjectTimeSchedule = "IT401 - 3:00 PM",
                            TeacherFullName = "Alice Williams",
                            TeacherId = new Guid("00000003-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2024, 10, 17, 15, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000003-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000014"),
                            BorrowerFullName = "Maria Santos",
                            BorrowerRole = "Student",
                            CreatedAt = new DateTime(2024, 9, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsHiddenFromUser = false,
                            ItemId = new Guid("00000005-0000-0000-0000-000000000010"),
                            ItemName = "USB Hub 7-Port",
                            ReservedFor = new DateTime(2024, 9, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Room = "Lab 102",
                            Status = "Expired",
                            StudentIdNumber = "2023-0002",
                            SubjectTimeSchedule = "IT201 - 10:00 AM",
                            TeacherFullName = "",
                            UpdatedAt = new DateTime(2024, 9, 10, 10, 31, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000004-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<Guid?>("OriginalUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int?>("UserRole")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ArchiveUsers");

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000001"),
                            ArchivedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "archived.admin@school.edu.ph",
                            FirstName = "Archived",
                            LastName = "Admin",
                            OriginalUserId = new Guid("00000001-0000-0000-0000-000000000005"),
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Inactive",
                            UserRole = 1,
                            Username = "archived.admin"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemModel")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("RfidUid")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("RfidUid")
                        .IsUnique();

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000001"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "10-foot HDMI 2.0 cable for display connections.",
                            ImageUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/items/item_01_hdmi_cable.png",
                            ItemMake = "Generic",
                            ItemModel = "Standard HDMI 2.0",
                            ItemName = "HDMI Cable 10ft",
                            ItemType = "Cable",
                            Location = "Lab Cabinet A",
                            RfidUid = "RFID-ITEM-001",
                            SerialNumber = "SN-HDMI-001",
                            Status = "Borrowed",
                            UpdatedAt = new DateTime(2025, 4, 11, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000002"),
                            Category = "MediaEquipment",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dual-channel wireless microphone system.",
                            ImageUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/items/item_02_wireless_mic.png",
                            ItemMake = "Shure",
                            ItemModel = "BLX288/PG58",
                            ItemName = "Wireless Microphone",
                            ItemType = "Microphone",
                            Location = "Media Room Shelf",
                            RfidUid = "RFID-ITEM-002",
                            SerialNumber = "SN-MIC-002",
                            Status = "Unavailable",
                            UpdatedAt = new DateTime(2025, 4, 20, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000003"),
                            Category = "MediaEquipment",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "3600-lumen portable LCD projector.",
                            ImageUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/items/item_03_projector.png",
                            ItemMake = "Epson",
                            ItemModel = "EB-X41",
                            ItemName = "Portable Projector",
                            ItemType = "Projector",
                            Location = "AV Room Cabinet",
                            RfidUid = "RFID-ITEM-003",
                            SerialNumber = "SN-PROJ-003",
                            Status = "Reserved",
                            UpdatedAt = new DateTime(2025, 4, 19, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000004"),
                            Category = "MediaEquipment",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Portable waterproof Bluetooth speaker.",
                            ImageUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/items/item_04_speaker.png",
                            ItemMake = "JBL",
                            ItemModel = "Charge 5",
                            ItemName = "Bluetooth Speaker",
                            ItemType = "Speaker",
                            Location = "Lab Cabinet B",
                            RfidUid = "RFID-ITEM-004",
                            SerialNumber = "SN-SPK-004",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 4, 10, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000005"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compact TKL mechanical keyboard with RGB.",
                            ImageUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/items/item_05_keyboard.png",
                            ItemMake = "Keychron",
                            ItemModel = "K2 Pro",
                            ItemName = "Mechanical Keyboard",
                            ItemType = "Peripheral",
                            Location = "Lab Cabinet A",
                            RfidUid = "RFID-ITEM-005",
                            SerialNumber = "SN-KB-005",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 3, 25, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000006"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "6-foot HDMI cable, retired from service.",
                            ImageUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/items/item_06_hdmi_short.png",
                            ItemMake = "Generic",
                            ItemName = "HDMI Cable 6ft",
                            ItemType = "Cable",
                            Location = "Storage Room",
                            RfidUid = "RFID-ITEM-006",
                            SerialNumber = "SN-HDMI-006",
                            Status = "Archived",
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000007"),
                            Category = "MediaEquipment",
                            Condition = "Defective",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "USB condenser microphone, defective.",
                            ImageUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/items/item_07_usb_mic.png",
                            ItemMake = "Blue",
                            ItemName = "USB Microphone",
                            ItemType = "Microphone",
                            Location = "Storage Room",
                            RfidUid = "RFID-ITEM-007",
                            SerialNumber = "SN-MIC-007",
                            Status = "Archived",
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000008"),
                            Category = "Electronics",
                            Condition = "NeedRepair",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wireless optical mouse, needs repair.",
                            ImageUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/items/item_08_mouse.png",
                            ItemMake = "Logitech",
                            ItemName = "Wireless Mouse",
                            ItemType = "Peripheral",
                            Location = "Storage Room",
                            RfidUid = "RFID-ITEM-008",
                            SerialNumber = "SN-MOUSE-008",
                            Status = "Archived",
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000009"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "15-foot extension wire, retired.",
                            ImageUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/items/item_09_extension.png",
                            ItemMake = "Generic",
                            ItemName = "Extension Wire 15ft",
                            ItemType = "Cable",
                            Location = "Storage Room",
                            RfidUid = "RFID-ITEM-009",
                            SerialNumber = "SN-EXT-009",
                            Status = "Archived",
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000010"),
                            Category = "Electronics",
                            Condition = "Refurbished",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "7-port USB 3.0 hub, refurbished.",
                            ImageUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/items/item_10_usb_hub.png",
                            ItemMake = "Anker",
                            ItemName = "USB Hub 7-Port",
                            ItemType = "Peripheral",
                            Location = "Storage Room",
                            RfidUid = "RFID-ITEM-010",
                            SerialNumber = "SN-HUB-010",
                            Status = "Archived",
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FrontStudentIdPictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("GuestImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsHiddenFromUser")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("IssuedById")
                        .HasColumnType("uuid");

                    b.Property<string>("IssuedByLastName")
                        .HasColumnType("text");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReservedFor")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Room")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("text");

                    b.Property<string>("StudentRfid")
                        .HasColumnType("text");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagUid")
                        .HasColumnType("text");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("text");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("LentItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000001"),
                            BorrowerFullName = "Juan Dela Cruz",
                            BorrowerRole = "Student",
                            CreatedAt = new DateTime(2025, 4, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            FrontStudentIdPictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/id-front/student_01_id_front.png",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("00000005-0000-0000-0000-000000000001"),
                            ItemName = "HDMI Cable 10ft",
                            LentAt = new DateTime(2025, 4, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            Room = "Lab 101",
                            Status = "Borrowed",
                            StudentIdNumber = "2023-0001",
                            StudentRfid = "RFID-STU-001",
                            SubjectTimeSchedule = "CS301 - 8:00 AM",
                            TagUid = "RFID-ITEM-001",
                            TeacherFullName = "",
                            UpdatedAt = new DateTime(2025, 4, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000004-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000002"),
                            BorrowerFullName = "Maria Santos",
                            BorrowerRole = "Student",
                            CreatedAt = new DateTime(2025, 4, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            FrontStudentIdPictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/id-front/student_02_id_front.png",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("00000005-0000-0000-0000-000000000002"),
                            ItemName = "Wireless Microphone",
                            ReservedFor = new DateTime(2025, 4, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            Room = "Lab 102",
                            Status = "Pending",
                            StudentIdNumber = "2023-0002",
                            StudentRfid = "RFID-STU-002",
                            SubjectTimeSchedule = "IT201 - 10:00 AM",
                            TagUid = "RFID-ITEM-002",
                            TeacherFullName = "",
                            UpdatedAt = new DateTime(2025, 4, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000004-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000003"),
                            BorrowerFullName = "Alice Williams",
                            BorrowerRole = "Teacher",
                            CreatedAt = new DateTime(2025, 4, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsHiddenFromUser = false,
                            ItemId = new Guid("00000005-0000-0000-0000-000000000003"),
                            ItemName = "Portable Projector",
                            ReservedFor = new DateTime(2025, 4, 26, 13, 0, 0, 0, DateTimeKind.Utc),
                            Room = "Room 201",
                            Status = "Approved",
                            SubjectTimeSchedule = "IT401 - 1:00 PM",
                            TagUid = "RFID-ITEM-003",
                            TeacherFullName = "Alice Williams",
                            TeacherId = new Guid("00000003-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2025, 4, 19, 11, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000003-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000004"),
                            BorrowerFullName = "Pedro Reyes",
                            BorrowerRole = "Student",
                            CreatedAt = new DateTime(2025, 4, 10, 13, 0, 0, 0, DateTimeKind.Utc),
                            FrontStudentIdPictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/id-front/student_03_id_front.png",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("00000005-0000-0000-0000-000000000004"),
                            ItemName = "Bluetooth Speaker",
                            LentAt = new DateTime(2025, 4, 10, 13, 0, 0, 0, DateTimeKind.Utc),
                            ReturnedAt = new DateTime(2025, 4, 14, 15, 0, 0, 0, DateTimeKind.Utc),
                            Room = "Lab 103",
                            Status = "Returned",
                            StudentIdNumber = "2023-0003",
                            StudentRfid = "RFID-STU-003",
                            SubjectTimeSchedule = "CS302 - 1:00 PM",
                            TagUid = "RFID-ITEM-004",
                            TeacherFullName = "",
                            UpdatedAt = new DateTime(2025, 4, 14, 15, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000004-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000005"),
                            BorrowerFullName = "Roberto Cruz",
                            BorrowerRole = "Teacher",
                            CreatedAt = new DateTime(2025, 4, 14, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsHiddenFromUser = false,
                            ItemId = new Guid("00000005-0000-0000-0000-000000000005"),
                            ItemName = "Mechanical Keyboard",
                            ReservedFor = new DateTime(2025, 4, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Room = "Room 202",
                            Status = "Expired",
                            SubjectTimeSchedule = "CS201 - 9:00 AM",
                            TagUid = "RFID-ITEM-005",
                            TeacherFullName = "Roberto Cruz",
                            TeacherId = new Guid("00000003-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2025, 4, 15, 9, 31, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000003-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRevoked")
                        .HasDatabaseName("IX_RefreshTokens_UserId_IsRevoked");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Rfid", b =>
                {
                    b.Property<string>("RfidUid")
                        .HasColumnType("text")
                        .HasColumnName("RfidUid");

                    b.Property<string>("RfidCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RfidCode");

                    b.HasKey("RfidUid");

                    b.ToTable("Rfids");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000001"),
                            Email = "superadmin@school.edu.ph",
                            FirstName = "Super",
                            LastName = "Admin",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Offline",
                            UserRole = "SuperAdmin",
                            Username = "sadmin"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000002"),
                            Email = "christian.admin@school.edu.ph",
                            FirstName = "Christian",
                            LastName = "Dela Cruz",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "christian"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000003"),
                            Email = "ejay.admin@school.edu.ph",
                            FirstName = "Ejay",
                            LastName = "Santos",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "ejay"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000004"),
                            Email = "stan.admin@school.edu.ph",
                            FirstName = "Stan",
                            LastName = "Reyes",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "stan"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000005"),
                            Email = "archived.admin@school.edu.ph",
                            FirstName = "Archived",
                            LastName = "Admin",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Inactive",
                            UserRole = "Admin",
                            Username = "archived.admin"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.ToTable("ArchiveStaff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000002"),
                            ArchivedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "archived.staff@school.edu.ph",
                            FirstName = "Archived",
                            LastName = "Staff",
                            OriginalUserId = new Guid("00000002-0000-0000-0000-000000000005"),
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Inactive",
                            UserRole = 2,
                            Username = "archived.staff",
                            Position = "Former Technician"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<byte[]>("BackStudentIdPicture")
                        .HasColumnType("bytea");

                    b.Property<string>("CityMunicipality")
                        .HasColumnType("text");

                    b.Property<string>("Course")
                        .HasColumnType("text");

                    b.Property<byte[]>("FrontStudentIdPicture")
                        .HasColumnType("bytea");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("bytea");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<string>("RfidUid")
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .HasColumnType("text");

                    b.ToTable("ArchiveStudents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000004"),
                            ArchivedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "archived.student@school.edu.ph",
                            FirstName = "Archived",
                            LastName = "Student",
                            OriginalUserId = new Guid("00000004-0000-0000-0000-000000000005"),
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Inactive",
                            UserRole = 4,
                            Username = "archived.student",
                            Course = "Bachelor of Science in Information Technology",
                            Section = "D",
                            StudentIdNumber = "2022-0099",
                            Year = "4th Year"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.ToTable("ArchiveTeachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000003"),
                            ArchivedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "archived.teacher@school.edu.ph",
                            FirstName = "Archived",
                            LastName = "Teacher",
                            OriginalUserId = new Guid("00000003-0000-0000-0000-000000000005"),
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Inactive",
                            UserRole = 3,
                            Username = "archived.teacher",
                            Department = "Former Department"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.ToTable("Staff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000001"),
                            Email = "carlos.mendoza@school.edu.ph",
                            FirstName = "Carlos",
                            LastName = "Mendoza",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "cmendoza",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000002"),
                            Email = "rosa.garcia@school.edu.ph",
                            FirstName = "Rosa",
                            LastName = "Garcia",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "rgarcia",
                            Position = "Equipment Manager"
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000003"),
                            Email = "ben.torres@school.edu.ph",
                            FirstName = "Ben",
                            LastName = "Torres",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "btorres",
                            Position = "IT Support"
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000004"),
                            Email = "liza.villanueva@school.edu.ph",
                            FirstName = "Liza",
                            LastName = "Villanueva",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "lvillanueva",
                            Position = "Asset Custodian"
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000005"),
                            Email = "archived.staff@school.edu.ph",
                            FirstName = "Archived",
                            LastName = "Staff",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Inactive",
                            UserRole = "Staff",
                            Username = "archived.staff",
                            Position = "Former Technician"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("BackStudentIdPictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrontStudentIdPictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("GeneratedPassword")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RfidCode")
                        .HasColumnType("text");

                    b.Property<string>("RfidUid")
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("StudentIdNumber")
                        .IsUnique()
                        .HasFilter("(\"StudentIdNumber\" IS NOT NULL AND \"StudentIdNumber\" <> '')");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000001"),
                            Email = "juan.delacruz@school.edu.ph",
                            FirstName = "Juan",
                            LastName = "Dela Cruz",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            PhoneNumber = "09171234501",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "jdelacruz",
                            BackStudentIdPictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/id-back/student_01_id_back.png",
                            CityMunicipality = "Quezon City",
                            Course = "Bachelor of Science in Computer Science",
                            FrontStudentIdPictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/id-front/student_01_id_front.png",
                            PostalCode = "1100",
                            ProfilePictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/profile/student_01_profile.png",
                            Province = "Metro Manila",
                            RfidUid = "RFID-STU-001",
                            Section = "A",
                            Street = "123 Rizal Street",
                            StudentIdNumber = "2023-0001",
                            Year = "3rd Year"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000002"),
                            Email = "maria.santos@school.edu.ph",
                            FirstName = "Maria",
                            LastName = "Santos",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            PhoneNumber = "09171234502",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "msantos",
                            BackStudentIdPictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/id-back/student_02_id_back.png",
                            CityMunicipality = "Makati City",
                            Course = "Bachelor of Science in Information Technology",
                            FrontStudentIdPictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/id-front/student_02_id_front.png",
                            PostalCode = "1200",
                            ProfilePictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/profile/student_02_profile.png",
                            Province = "Metro Manila",
                            RfidUid = "RFID-STU-002",
                            Section = "B",
                            Street = "456 Mabini Avenue",
                            StudentIdNumber = "2023-0002",
                            Year = "2nd Year"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000003"),
                            Email = "pedro.reyes@school.edu.ph",
                            FirstName = "Pedro",
                            LastName = "Reyes",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            PhoneNumber = "09171234503",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "preyes",
                            BackStudentIdPictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/id-back/student_03_id_back.png",
                            CityMunicipality = "Pasig City",
                            Course = "Bachelor of Science in Computer Science",
                            FrontStudentIdPictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/id-front/student_03_id_front.png",
                            PostalCode = "1600",
                            ProfilePictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/profile/student_03_profile.png",
                            Province = "Metro Manila",
                            RfidUid = "RFID-STU-003",
                            Section = "A",
                            Street = "789 Bonifacio Road",
                            StudentIdNumber = "2023-0003",
                            Year = "3rd Year"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000004"),
                            Email = "ana.garcia@school.edu.ph",
                            FirstName = "Ana",
                            LastName = "Garcia",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            PhoneNumber = "09171234504",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "agarcia",
                            BackStudentIdPictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/id-back/student_04_id_back.png",
                            CityMunicipality = "Mandaluyong City",
                            Course = "Bachelor of Multimedia Arts",
                            FrontStudentIdPictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/id-front/student_04_id_front.png",
                            PostalCode = "1550",
                            ProfilePictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/profile/student_04_profile.png",
                            Province = "Metro Manila",
                            RfidUid = "RFID-STU-004",
                            Section = "C",
                            Street = "321 Luna Street",
                            StudentIdNumber = "2023-0004",
                            Year = "1st Year"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000005"),
                            Email = "archived.student@school.edu.ph",
                            FirstName = "Archived",
                            LastName = "Student",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            PhoneNumber = "09170000000",
                            Status = "Inactive",
                            UserRole = "Student",
                            Username = "archived.student",
                            BackStudentIdPictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/id-back/student_05_id_back.png",
                            CityMunicipality = "Taguig City",
                            Course = "Bachelor of Science in Information Technology",
                            FrontStudentIdPictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/id-front/student_05_id_front.png",
                            PostalCode = "1630",
                            ProfilePictureUrl = "https://oeyoyyxeluzaeckwpcsa.supabase.co/storage/v1/object/public/technical-bucket/students/profile/student_05_profile.png",
                            Province = "Metro Manila",
                            Section = "D",
                            Street = "999 Old Street",
                            StudentIdNumber = "2022-0099",
                            Year = "4th Year"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000001"),
                            Email = "alice.williams@school.edu.ph",
                            FirstName = "Alice",
                            LastName = "Williams",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "awilliams",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000002"),
                            Email = "roberto.cruz@school.edu.ph",
                            FirstName = "Roberto",
                            LastName = "Cruz",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "rcruz",
                            Department = "Computer Science"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000003"),
                            Email = "elena.fernandez@school.edu.ph",
                            FirstName = "Elena",
                            LastName = "Fernandez",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "efernandez",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000004"),
                            Email = "jose.miranda@school.edu.ph",
                            FirstName = "Jose",
                            LastName = "Miranda",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "jmiranda",
                            Department = "Multimedia Arts"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000005"),
                            Email = "archived.teacher@school.edu.ph",
                            FirstName = "Archived",
                            LastName = "Teacher",
                            PasswordHash = "$2a$04$WuSJZNktuI9FLcH.Az5HpeKJFhyNCxNzz7tR3jTVdzusa7qAJBBSK",
                            Status = "Inactive",
                            UserRole = "Teacher",
                            Username = "archived.teacher",
                            Department = "Former Department"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ActivityLog", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.LentItems", "LentItem")
                        .WithMany()
                        .HasForeignKey("LentItemId");

                    b.Navigation("ActorUser");

                    b.Navigation("Item");

                    b.Navigation("LentItem");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveLentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Item");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("LentItems")
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Staff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Navigation("LentItems");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
