// <auto-generated />
using System;
using BackendTechnicalAssetsManagement.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendTechnicalAssetsManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419043217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BorrowedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemSerialNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("LentItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewStatus")
                        .HasColumnType("text");

                    b.Property<string>("PreviousStatus")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReservedFor")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LentItemId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemModel")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("RfidUid")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ArchiveItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000005"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemMake = "Generic",
                            ItemName = "HDMI Cable 6ft",
                            ItemType = "Cable",
                            SerialNumber = "SN-HDMI-007",
                            Status = "Archived",
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000006"),
                            Category = "MediaEquipment",
                            Condition = "Defective",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemMake = "Blue",
                            ItemName = "USB Microphone",
                            ItemType = "Microphone",
                            SerialNumber = "SN-MIC-008",
                            Status = "Archived",
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveLentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FrontStudentIdPictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("GuestImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsHiddenFromUser")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReservedFor")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("text");

                    b.Property<string>("StudentRfid")
                        .HasColumnType("text");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagUid")
                        .HasColumnType("text");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("text");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("ArchiveLentItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000007"),
                            BorrowerFullName = "David Ramos",
                            BorrowerRole = "Teacher",
                            CreatedAt = new DateTime(2025, 1, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsHiddenFromUser = false,
                            ItemId = new Guid("00000005-0000-0000-0000-000000000007"),
                            ItemName = "HDMI Cable 6ft",
                            LentAt = new DateTime(2025, 1, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            ReturnedAt = new DateTime(2025, 1, 14, 11, 0, 0, 0, DateTimeKind.Utc),
                            Room = "Room 301",
                            Status = "Returned",
                            SubjectTimeSchedule = "MA101 - 11:00 AM",
                            TeacherFullName = "David Ramos",
                            TeacherId = new Guid("00000003-0000-0000-0000-000000000004"),
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000003-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<Guid?>("OriginalUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int?>("UserRole")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ArchiveUsers");

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000001"),
                            ArchivedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ana.reyes@gmail.com",
                            FirstName = "Ana",
                            LastName = "Reyes",
                            OriginalUserId = new Guid("00000001-0000-0000-0000-000000000004"),
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Inactive",
                            UserRole = 1,
                            Username = "areyes"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemModel")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("RfidUid")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("RfidUid")
                        .IsUnique();

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000001"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemMake = "Generic",
                            ItemName = "HDMI Cable 10ft",
                            ItemType = "Cable",
                            SerialNumber = "SN-HDMI-001",
                            Status = "Borrowed",
                            UpdatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000002"),
                            Category = "MediaEquipment",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemMake = "Shure",
                            ItemName = "Wireless Microphone",
                            ItemType = "Microphone",
                            SerialNumber = "SN-MIC-002",
                            Status = "Borrowed",
                            UpdatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000003"),
                            Category = "MediaEquipment",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemMake = "JBL",
                            ItemName = "Portable Bluetooth Speaker",
                            ItemType = "Speaker",
                            RfidUid = "RFID-ITEM-003",
                            SerialNumber = "SN-SPK-003",
                            Status = "Available",
                            UpdatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000004"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemMake = "Logitech",
                            ItemName = "Wireless Mouse",
                            ItemType = "Peripheral",
                            SerialNumber = "SN-MOUSE-004",
                            Status = "Borrowed",
                            UpdatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000005"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemMake = "Keychron",
                            ItemName = "Mechanical Keyboard",
                            ItemType = "Peripheral",
                            RfidUid = "RFID-ITEM-005",
                            SerialNumber = "SN-KB-005",
                            Status = "Available",
                            UpdatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000006"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemMake = "Generic",
                            ItemName = "Extension Wire 15ft",
                            ItemType = "Cable",
                            RfidUid = "RFID-ITEM-006",
                            SerialNumber = "SN-EXT-006",
                            Status = "Available",
                            UpdatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000007"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemMake = "Generic",
                            ItemName = "HDMI Cable 6ft",
                            ItemType = "Cable",
                            SerialNumber = "SN-HDMI-007",
                            Status = "Archived",
                            UpdatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000008"),
                            Category = "MediaEquipment",
                            Condition = "Defective",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemMake = "Blue",
                            ItemName = "USB Microphone",
                            ItemType = "Microphone",
                            SerialNumber = "SN-MIC-008",
                            Status = "Archived",
                            UpdatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FrontStudentIdPictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("GuestImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsHiddenFromUser")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("IssuedById")
                        .HasColumnType("uuid");

                    b.Property<string>("IssuedByLastName")
                        .HasColumnType("text");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReservedFor")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("text");

                    b.Property<string>("StudentRfid")
                        .HasColumnType("text");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagUid")
                        .HasColumnType("text");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("text");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("LentItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000001"),
                            BorrowerFullName = "John Doe",
                            BorrowerRole = "Student",
                            CreatedAt = new DateTime(2025, 4, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsHiddenFromUser = false,
                            ItemId = new Guid("00000005-0000-0000-0000-000000000001"),
                            ItemName = "HDMI Cable 10ft",
                            LentAt = new DateTime(2025, 4, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            Room = "Lab 101",
                            Status = "Borrowed",
                            StudentIdNumber = "2023-0001",
                            SubjectTimeSchedule = "CS301 - 8:00 AM",
                            TeacherFullName = "",
                            UpdatedAt = new DateTime(2025, 4, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000004-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000002"),
                            BorrowerFullName = "Jane Smith",
                            BorrowerRole = "Student",
                            CreatedAt = new DateTime(2025, 4, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsHiddenFromUser = false,
                            ItemId = new Guid("00000005-0000-0000-0000-000000000003"),
                            ItemName = "Portable Bluetooth Speaker",
                            LentAt = new DateTime(2025, 4, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            ReturnedAt = new DateTime(2025, 4, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            Room = "Lab 102",
                            Status = "Returned",
                            StudentIdNumber = "2023-0002",
                            SubjectTimeSchedule = "IT201 - 10:00 AM",
                            TeacherFullName = "",
                            UpdatedAt = new DateTime(2025, 4, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000004-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000003"),
                            BorrowerFullName = "Peter Jones",
                            BorrowerRole = "Student",
                            CreatedAt = new DateTime(2025, 4, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            IsHiddenFromUser = false,
                            ItemId = new Guid("00000005-0000-0000-0000-000000000002"),
                            ItemName = "Wireless Microphone",
                            LentAt = new DateTime(2025, 4, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            Room = "Lab 103",
                            Status = "Borrowed",
                            StudentIdNumber = "2023-0003",
                            SubjectTimeSchedule = "CS302 - 1:00 PM",
                            TeacherFullName = "",
                            UpdatedAt = new DateTime(2025, 4, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000004-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000004"),
                            BorrowerFullName = "Alice Williams",
                            BorrowerRole = "Teacher",
                            CreatedAt = new DateTime(2025, 4, 13, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsHiddenFromUser = false,
                            ItemId = new Guid("00000005-0000-0000-0000-000000000004"),
                            ItemName = "Wireless Mouse",
                            LentAt = new DateTime(2025, 4, 13, 15, 0, 0, 0, DateTimeKind.Utc),
                            Room = "Room 201",
                            Status = "Borrowed",
                            SubjectTimeSchedule = "IT401 - 3:00 PM",
                            TeacherFullName = "Alice Williams",
                            TeacherId = new Guid("00000003-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2025, 4, 13, 15, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000003-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000005"),
                            BorrowerFullName = "Roberto Cruz",
                            BorrowerRole = "Teacher",
                            CreatedAt = new DateTime(2025, 3, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsHiddenFromUser = false,
                            ItemId = new Guid("00000005-0000-0000-0000-000000000005"),
                            ItemName = "Mechanical Keyboard",
                            LentAt = new DateTime(2025, 3, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            ReturnedAt = new DateTime(2025, 4, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Room = "Room 202",
                            Status = "Returned",
                            SubjectTimeSchedule = "CS201 - 9:00 AM",
                            TeacherFullName = "Roberto Cruz",
                            TeacherId = new Guid("00000003-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2025, 4, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000003-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000001"),
                            Email = "superadmin@gmail.com",
                            FirstName = "Super",
                            LastName = "Admin",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Active",
                            UserRole = "SuperAdmin",
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000002"),
                            Email = "maria.santos@gmail.com",
                            FirstName = "Maria",
                            LastName = "Santos",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Active",
                            UserRole = "Admin",
                            Username = "msantos"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000003"),
                            Email = "juan.delacruz@gmail.com",
                            FirstName = "Juan",
                            LastName = "Dela Cruz",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Active",
                            UserRole = "Admin",
                            Username = "jdelacruz"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000004"),
                            Email = "ana.reyes@gmail.com",
                            FirstName = "Ana",
                            LastName = "Reyes",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Inactive",
                            UserRole = "Admin",
                            Username = "areyes"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.ToTable("ArchiveStaff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000002"),
                            ArchivedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "miguel.torres@gmail.com",
                            FirstName = "Miguel",
                            LastName = "Torres",
                            OriginalUserId = new Guid("00000002-0000-0000-0000-000000000003"),
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Inactive",
                            UserRole = 2,
                            Username = "mtorres",
                            Position = "IT Support"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<byte[]>("BackStudentIdPicture")
                        .HasColumnType("bytea");

                    b.Property<string>("CityMunicipality")
                        .HasColumnType("text");

                    b.Property<string>("Course")
                        .HasColumnType("text");

                    b.Property<byte[]>("FrontStudentIdPicture")
                        .HasColumnType("bytea");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("bytea");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<string>("RfidUid")
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .HasColumnType("text");

                    b.ToTable("ArchiveStudents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000004"),
                            ArchivedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sofia.gonzales@gmail.com",
                            FirstName = "Sofia",
                            LastName = "Gonzales",
                            OriginalUserId = new Guid("00000004-0000-0000-0000-000000000006"),
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Inactive",
                            UserRole = 4,
                            Username = "sgonzales",
                            Course = "Computer Science",
                            Section = "B",
                            StudentIdNumber = "2024-0001",
                            Year = "1st Year"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.ToTable("ArchiveTeachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000003"),
                            ArchivedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david.ramos@gmail.com",
                            FirstName = "David",
                            LastName = "Ramos",
                            OriginalUserId = new Guid("00000003-0000-0000-0000-000000000004"),
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Inactive",
                            UserRole = 3,
                            Username = "dramos",
                            Department = "Multimedia Arts"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.ToTable("Staff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000001"),
                            Email = "carlos.mendoza@gmail.com",
                            FirstName = "Carlos",
                            LastName = "Mendoza",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Active",
                            UserRole = "Staff",
                            Username = "cmendoza",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000002"),
                            Email = "rosa.garcia@gmail.com",
                            FirstName = "Rosa",
                            LastName = "Garcia",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Active",
                            UserRole = "Staff",
                            Username = "rgarcia",
                            Position = "Equipment Manager"
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000003"),
                            Email = "miguel.torres@gmail.com",
                            FirstName = "Miguel",
                            LastName = "Torres",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Inactive",
                            UserRole = "Staff",
                            Username = "mtorres",
                            Position = "IT Support"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("BackStudentIdPictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrontStudentIdPictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("GeneratedPassword")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RfidUid")
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("StudentIdNumber")
                        .IsUnique()
                        .HasFilter("(\"StudentIdNumber\" IS NOT NULL AND \"StudentIdNumber\" <> '')");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000001"),
                            Email = "john.doe@gmail.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Active",
                            UserRole = "Student",
                            Username = "jdoe",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "2023-0001",
                            Year = "3rd Year"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000002"),
                            Email = "jane.smith@gmail.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Active",
                            UserRole = "Student",
                            Username = "jsmith",
                            CityMunicipality = "",
                            Course = "Information Technology",
                            PostalCode = "",
                            Province = "",
                            Section = "B",
                            Street = "",
                            StudentIdNumber = "2023-0002",
                            Year = "2nd Year"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000003"),
                            Email = "peter.jones@gmail.com",
                            FirstName = "Peter",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Active",
                            UserRole = "Student",
                            Username = "pjones",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "2023-0003",
                            Year = "3rd Year"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000004"),
                            Email = "maria.lopez@gmail.com",
                            FirstName = "Maria",
                            LastName = "Lopez",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Active",
                            UserRole = "Student",
                            Username = "mlopez",
                            CityMunicipality = "",
                            Course = "Multimedia Arts",
                            PostalCode = "",
                            Province = "",
                            Section = "C",
                            Street = "",
                            StudentIdNumber = "2023-0004",
                            Year = "1st Year"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000005"),
                            Email = "carlos.rivera@gmail.com",
                            FirstName = "Carlos",
                            LastName = "Rivera",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Active",
                            UserRole = "Student",
                            Username = "crivera",
                            CityMunicipality = "",
                            Course = "Information Technology",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "2023-0005",
                            Year = "2nd Year"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000006"),
                            Email = "sofia.gonzales@gmail.com",
                            FirstName = "Sofia",
                            LastName = "Gonzales",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Inactive",
                            UserRole = "Student",
                            Username = "sgonzales",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "B",
                            Street = "",
                            StudentIdNumber = "2024-0001",
                            Year = "1st Year"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000001"),
                            Email = "alice.williams@gmail.com",
                            FirstName = "Alice",
                            LastName = "Williams",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Active",
                            UserRole = "Teacher",
                            Username = "awilliams",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000002"),
                            Email = "roberto.cruz@gmail.com",
                            FirstName = "Roberto",
                            LastName = "Cruz",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Active",
                            UserRole = "Teacher",
                            Username = "rcruz",
                            Department = "Computer Science"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000003"),
                            Email = "elena.fernandez@gmail.com",
                            FirstName = "Elena",
                            LastName = "Fernandez",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Active",
                            UserRole = "Teacher",
                            Username = "efernandez",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000004"),
                            Email = "david.ramos@gmail.com",
                            FirstName = "David",
                            LastName = "Ramos",
                            PasswordHash = "$2a$11$2MsPT1w1IrQKGjo7.ZZ6duUDE9aS0P6P5qxULhHe//cLWRgRBXw/i",
                            Status = "Inactive",
                            UserRole = "Teacher",
                            Username = "dramos",
                            Department = "Multimedia Arts"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ActivityLog", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.LentItems", "LentItem")
                        .WithMany()
                        .HasForeignKey("LentItemId");

                    b.Navigation("ActorUser");

                    b.Navigation("Item");

                    b.Navigation("LentItem");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveLentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Item");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("LentItems")
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Staff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Navigation("LentItems");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
